services:
  editor:
    build:
      context: .
      args:
        NODE_MAJOR: "${NODE_MAJOR:-24}"

    ports:
      - "127.0.0.1:5173:5173"

    volumes:
      # 作業空間
      - type: bind
        source: .
        target: /workspace

      # DependencyをHostではなくDocker内に保持する
      - type: volume
        source: node_modules
        target: /workspace/node_modules

volumes:
  node_modules: